# Course Configuration
#
# Customize me!

# location of Git repos on disk
git: /mit/6.EXOUT/git/ia00
# location of exout on the web
http: https://example.com/exout

# optional: custom instructions to the student
#   can include %{kind}, %{proj}, %{user}, and %{url} substitutions
#instructions: >
#  <p>Have fun!</p>
